import Head from 'next/head'
import Image from 'next/image'
import { Content, Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from './components/Navbar'
import InfoBar from './components/InfoBar'
import Body from './components/Body'
import Contentbody from './components/Contentbody'
import Sidebar from './components/Sidebar'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <InfoBar />
      {/* <Body>
        <Contentbody />
        <Sidebar />
      </Body> */}
    </>
  )
}
